In [1]:
#Numpy- NumPy is a Python library used to perform mathematical tasks, especially with arrays and matrices.
#Numpy stands for numerical python

# NumPy Overview
# NumPy uses arrays to perform operations and store data efficiently.

# Why Arrays?
# Arrays store data in continuous memory locations.
# This makes data access faster compared to Python lists.

# Key Advantages of NumPy Arrays(its the difference also between lists and arrays):
# Speed: Much faster than lists for numerical tasks.
# Efficiency: Consumes less memory due to continuous memory allocation.
# Convenient Operations: Supports mathematical operations like addition, multiplication, and trigonometric functions directly on arrays.

# Definition:
# Broadcasting in NumPy is the ability to perform element-wise operations on arrays of different shapes — by automatically expanding 
#the smaller array to match the shape of the larger one.
# 🎯 In Simple Words:# You can add, subtract, multiply, etc., arrays of different shapes, and NumPy will stretch the smaller array without copying data.

In [4]:
!pip install numpy

#pip install numpy
#This is the normal Python command to install the NumPy library from the Python Package Index (PyPI).

#This is ! (Exclamation mark)
#In Jupyter Notebook or Colab, putting ! before a command allows you to run system shell commands directly from the notebook.

# Command Prompt = The tool / application (like CMD.exe in Windows)
# System Shell Command = The instructions / commands you type in (like mkdir, cd, pip install numpy)

# Example:
# If you open Command Prompt (CMD) and type:
# pip install numpy
# pip install numpy is the shell command.
# The CMD window you are typing into is the Command Prompt.

In [1]:
import numpy
arr=numpy.arange(4)
print(type(arr),arr)


<class 'numpy.ndarray'> [0 1 2 3]


In [12]:
# ✅ 1. Scalar (0-D array)
# A scalar is a single number (just one value), like 5, 3.14, etc.
#it has no direction
#used to perform arithmetic operations

# | Code                 | Meaning                                           |
# | -------------------- | ------------------------------------------------- |
# | `import numpy`       | Import the NumPy library.                         |
# | `import numpy as np` | Import NumPy and use **`np`** as a shortcut name. |

    
import numpy as np

a = np.array(7)
print(a)            # Output: 7
print(a.ndim)       # 0 (scalar has 0 dimensions) #prints the number of dimensions (axes) of the array.


7
0


In [24]:
#  2. Vector (1-D array)
# A vector is a 1-dimensional array of numbers.
# It can be thought of as a list like [1, 2, 3].
# 1D array → No "vertical only" or "horizontal only" → Just a list of values
# Vertical axis appears only in 2D or higher arrays.
# Technically, a 1D array has one direction → It’s a linear sequence.
# But it is NOT explicitly "horizontal" or "vertical" because NumPy doesn’t assign a direction to 1D arrays.

v = np.array([1, 2, 3])
print(v)            # Output: [1 2 3]
print(v.ndim)       # 1 (vector)


[1 2 3]
1


In [28]:
# ✅ 3. Matrix (2-D array)
# A matrix is a 2-dimensional array of numbers — rows and columns.
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print(m)
# Output:
# [[1 2 3]
#  [4 5 6]]

print(m.ndim)       # 2 (matrix)

#Are the number of rows and columns always the same in a matrix?
#❌ No, in general matrices do not have to be square.
# | Matrix Type            | Description      | Example Shape      |
# | ---------------------- | ---------------- | ------------------ |
# | **Square Matrix**      | Rows = Columns   | `2x2`, `3x3`, etc. |
# | **Rectangular Matrix** | Rows ≠ Columns   | `2x3`, `3x2`, etc. |
# | **Row Vector**         | 1 row, N columns | `1x3`              |
# | **Column Vector**      | N rows, 1 column | `3x1`              |


[[1 2 3]
 [4 5 6]]
2


In [5]:
#✅ 1. Row Vector
#A row vector is a 2D array with 1 row and N columns.
import numpy as np

row_vec = np.array([[1, 2, 3]])
print(row_vec)
print("Shape:", row_vec.shape)  # (1, 3)


# | **Number** | **Meaning**           |
# | ---------- | --------------------- |
# | `1`        | **Number of rows**    |
# | `3`        | **Number of columns** |


[[1 2 3]]
Shape: (1, 3)


In [32]:
#  2. Column Vector
# A column vector is a 2D array with N rows and 1 column
col_vec = np.array([[1],
                    [2],
                    [3]])
print(col_vec)
print("Shape:", col_vec.shape)  # (3, 1)


[[1]
 [2]
 [3]]
Shape: (3, 1)


In [17]:
import numpy as np
arr=np.arange(4)
arr.size
print(arr.size)
arr.shape
arr[0]=100
print(arr.shape)
print(arr.size)
print(arr,type(arr))

4
(4,)
4
[100   1   2   3] <class 'numpy.ndarray'>


In [46]:
import numpy as np
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np
arr2=np.arange(10)
print(arr2.size)
print(arr2.shape)
#shape shows number of rows and columns

10
(10,)


In [74]:
import numpy as np
arr3=np.array([10,20,30])
arr4=np.array([30,40,50,60,70])
print(arr3.shape,arr4.shape)
print(arr3,arr4)

(3,) (5,)
[10 20 30] [30 40 50 60 70]


In [78]:
import numpy as np
arr5=np.array([10,20,30])
arr6=np.array([[30,40,50,60,70]])
print(arr5.shape,arr6.shape)
print(arr5,arr6)
#1 row 5 column...row vector

(3,) (1, 5)
[10 20 30] [[30 40 50 60 70]]


In [92]:
import numpy as np
arr7=np.array([[[10,20,30],
             [50,100,500]]])
print(arr7.shape)
print(arr7)

arr8=arr7.reshape((1,6))
print(arr8)
#2 rows, three columns...column vector

(1, 2, 3)
[[[ 10  20  30]
  [ 50 100 500]]]
[[ 10  20  30  50 100 500]]


In [94]:
np.zeros((2,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [96]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [98]:
arr9=np.arange(10, dtype="float")
arr9=arr9.reshape(5,2)
arr9

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [106]:
arr9=np.arange(10, dtype="float")
arr9=arr9.reshape(5,2)
arr9
np.ones_like(arr9)
#in ones we give the shape by ourself, ones_like takes the shape by looking at the array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
arr9=np.arange(10, dtype="float")
arr9=arr9.reshape(5,2)
arr9
np.zeros_like(arr9)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [116]:
#different functions to make different arrays
a=np.array([1,2,3])       #1D array
b=np.array([[1,2],[3,4]]) #2D array
c=np.zeros((2,3))         
d=np.ones((3,3))
e=np.eye(3)
f=np.arange(1,10,2)
print(f)

[1 3 5 7 9]


In [118]:
import numpy as np

a = np.array([1, 2, 3])          # 1D array → shape: (3,)
b = np.array([[1, 2], [3, 4]])   # 2D array → shape: (2, 2)
c = np.zeros((2, 3))             # 2D array of zeros → shape: (2, 3)
d = np.ones((3, 3))              # 2D array of ones → shape: (3, 3)
e = np.eye(3)                    # Identity matrix (3x3) → diagonal ones
f = np.arange(1, 10, 2)          # 1D array → range from 1 to 9 with step 2 → [1 3 5 7 9]

print(f)                         # Output: [1 3 5 7 9]


[1 3 5 7 9]
