In [3]:
#slicing and indexing
import numpy as np
arr=np.array([[10,20,30],[40,50,60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [7]:
arr[0]

array([10, 20, 30])

In [9]:
arr[1]

array([40, 50, 60])

In [13]:
arr[0][0]

10

In [15]:
arr[0][1]

20

In [17]:
arr[0][2]

30

In [19]:
arr[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
arr[:,1]

array([20, 50])

In [25]:
arr[1][2]

60

In [102]:
print(arr[0:,0:2])
print(arr[0:,0:2].flatten()) #flatten is a function which is used to convert 2d array into 1d array

[[10 20]
 [40 50]]
[10 20 40 50]


In [133]:
#filtering data from array
arr1=np.array([[10,20,30],[40,50,60]])
print(arr1)
print(arr1[arr1>25])
print(arr1[arr1<50])
print((arr1[arr1>25]) & (arr1[arr1>50]) )

[[10 20 30]
 [40 50 60]]
[30 40 50 60]
[10 20 30 40]
[28 40 48 60]


In [135]:
arr2=np.array([[10,20,30],[40,50,60]])
arr2+10

array([[20, 30, 40],
       [50, 60, 70]])

In [137]:
arr3=np.array([[10,20,30],[40,50,60]])
arr4=np.array([[10,20,30],[40,50,60]])
print(arr3+arr4)

[[ 20  40  60]
 [ 80 100 120]]


In [143]:
arr4=np.array([[10,20,30],[40,50,60]])
arr5=np.array([[10,20,30],[40,50]])
print(arr4+arr5)
#elements of same size can be added only through addition

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [149]:
#multiplication of 2d with 1d
a=np.array([[1,2,3],[4,5,6]])
b=np.array([2,4,6])
result=np.dot(a,b)
print(result)


[28 64]


In [163]:
#multiplication of 2d with 2d
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[2,4],[10,20],[20,30]])
result=np.dot(a1,b1)
print(result)


[[ 82 134]
 [178 296]]


In [153]:
m=np.array([[1,2,3],[2,3,4]])
n=np.array([[1,2],[2,3],[3,4]])
result1=np.dot(n,m)
print(result1)

[[ 5  8 11]
 [ 8 13 18]
 [11 18 25]]


In [165]:
# 3*n n*4
m1=np.array([[1,2,3],[2,3,4],[4,5,6]])
n1=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
result2=np.dot(m1,n1)
print(result2)

[[14 20 26 32]
 [20 29 38 47]
 [32 47 62 77]]


In [171]:
data=np.array([[1,2],[3,4]])
np.sum(data)

10

In [173]:
np.mean(data)

2.5

In [175]:
np.min(data,axis=0)

array([1, 2])

In [177]:
np.max(data,axis=0)

array([3, 4])

In [179]:
np.min(data,axis=1)

array([1, 3])

In [181]:
np.max(data,axis=1)

array([2, 4])

In [195]:
np.sum(data,axis=0)

array([4, 6])

In [197]:
np.sum(data,axis=1)

array([3, 7])

In [185]:
x=np.array([[1,2],
           [2,3]])
y=np.array([[5,6]])
np.vstack((x,y))

# np.vstack() – Vertical Stack
# np.vstack((x, y)) means stack arrays vertically (row-wise).

# Think of it like adding y as a new row below x.

# np.hstack() – Horizontal Stack
# np.hstack((x, y)) means stack arrays horizontally (column-wise).

# You need to match the number of rows, not columns.

# Each array is placed side by side.

array([[1, 2],
       [2, 3],
       [5, 6]])

In [191]:
x1=np.array([[1,2],
           [2,3]])
y1=np.array([[5,6],
            [7,8]])
np.vstack((x1,y1))


array([[1, 2],
       [2, 3],
       [5, 6],
       [7, 8]])

In [193]:
np.hstack((x1,y1))

array([[1, 2, 5, 6],
       [2, 3, 7, 8]])

In [ ]:
#how to read a data from a file using numpy
#broadcasting