In [9]:
# NumPy was developed by Travis Oliphant in 2005.
#numpy is a library of python through  which we can handle large amount of data using arrays instead of list.
#it is used to perform arithmetic calculation on numeric data.


#C is the fastest programming language because it is closest to hardware, it is used for OS,
#embedded system(An embedded system is a small computer built into a device to perform a specific task.).
# Washing Machine	Controls washing cycles
# Microwave Oven	Manages heating and timing

# Universal Function (ufunc) in NumPy =
# A built-in, fast, vectorized function that performs element-wise operations on arrays.
# It’s written in C for speed, but you call it like normal Python functions.
#Universal function: functions that can be applied over each elements

# | Category            | Function Examples                       |
# | ------------------- | --------------------------------------- |
# | **Arithmetic**      | `add`, `subtract`, `multiply`, `divide` |
# | **Trigonometric**   | `sin`, `cos`, `tan`                     |
# | **Exponential/Log** | `exp`, `log`, `log10`                   |
# | **Comparison**      | `greater`, `less`, `equal`              |
# | **Statistical**     | `minimum`, `maximum`, `mean`, `std`     |



# Why do people still use Python if it's slower?
# Python is easy to write and learn.

# Python is good for prototyping.

# Many libraries like NumPy, TensorFlow, PyTorch use C/C++ internally for speed but give Python interface for simplicity.

# NumPy and C: How are they related?
# NumPy is a Python library, but internally, it uses C language for the heavy work (like calculations).

# That’s why NumPy is very fast compared to normal Python loops.


#Numpy stands for numerical python

# NumPy Overview
# NumPy uses arrays to perform operations and store data efficiently.

# Why Arrays?
# Arrays store data in continuous memory locations.
# This makes data access faster compared to Python lists.

# Key Advantages of NumPy Arrays(its the difference also between lists and arrays):
# Speed: Much faster than lists for numerical tasks.
# Efficiency: Consumes less memory due to continuous memory allocation.
# Convenient Operations: Supports mathematical operations like addition, multiplication, and trigonometric functions directly on arrays.

# Definition:
# Broadcasting in NumPy is the ability to perform element-wise operations on arrays of different shapes — by automatically expanding 
#the smaller array to match the shape of the larger one.
# 🎯 In Simple Words:# You can add, subtract, multiply, etc., arrays of different shapes, and NumPy will stretch the smaller array without copying data.

In [7]:
import numpy as np
temperatures=np.array([32.5,31.8,33.0,35.2,36.6])
average=np.mean(temperatures)
print(average)

33.82


In [11]:
# features of numpy: 
# 1. consumes less memory
# 2. easy math operation
# 3. used in almost all data fields AI,DS,Data Analysis


In [13]:
# Use of Numpy:
# 1.Data Science
# 2.Machine Learning and AI(used in tensorflow and pytorch)
# 3.Stock market and finance
# 4.Image processing(photoshop tools)
# 5. Scientific Computing
# Solving mathematical problems: linear algebra, calculus,
# 6. Deep Learning
# Creating input data structures (e.g., image tensors)
# Normalization and augmentation of data
# 7. Mathematical Computations
# Matrix multiplication, inversion, dot products
# Statistical functions (mean, median, std)
# 8. Computer Graphics & Simulations
# Modeling transformations in 2D/3D space
# Creating simulations using multi-dimensional arrays

In [1]:
#  difference between Python Lists and NumPy Arrays
#A NumPy ndarray (n-dimensional array) is the primary data structure of the NumPy library, used to store elements of the same data type in effiecient way
#in a multidimensional format. It is faster than actual list,uses less memory and perform mathematical operations directly without using any loop.


# | Feature                      | **Python List**                                                       | **NumPy Array**                                                      |
# | ---------------------------- | --------------------------------------------------------------------- | -------------------------------------------------------------------- |
# |Actual existence?             | Built-in data structure                                               |  Provided by NumPy library
# | **Data Type**                | **Heterogeneous** – can store different types (int, float, str, etc.) | **Homogeneous** – all elements must be of the same type              |
# | **Speed**                    | Slower – not optimized for numerical computation                      | Faster – optimized using C backend and vectorized operations         |
# | **Memory Efficiency**        | Consumes more memory due to dynamic typing                            | Consumes less memory – fixed data types and continuous memory        |
# | **Mathematical Operations**  | Not supported directly (e.g., `a + b` concatenates lists)             | Element-wise operations (e.g., `a + b` adds elements)                |
# | **Functionality**            | Basic: append, pop, slice, etc.                                       | Rich:broadcasting, statistical operations, reshaping       |
# | **Indexing**                 | Basic (single level)                                                  | Advanced (multi-dimensional)                |

#In NumPy, multidimensional indexing lets you access elements in arrays with 2 or more dimensions using row and column indices, or even more.

In [7]:
python_list=[1,2,3,4,5]
print(python_list)

import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)


# Printing a Python list shows elements separated by commas,
# while printing a NumPy array shows elements separated by spaces (no commas).

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [1]:
# An array is a data structure that stores elements of the same data type in a fixed-size, indexed, and ordered format.
# A fixed-size array means that once an array is created, its size (number of elements) cannot be changed directly.

# In Python, arrays are commonly created using the NumPy library, where they are called ndarray and support multi-dimensional storage 
# and fast numerical computations.

In [3]:
# | Array Type   | Description                   | Example                                        |
# | ------------ | ----------------------------- | ---------------------------------------------- |
# | **1D Array** | Single row or column (vector) | `np.array([1, 2, 3])`                          |
# | **2D Array** | Matrix (rows and columns)     | `np.array([[1, 2], [3, 4]])`                   |
# | **3D Array** | Stack of matrices/2d-arrays   | `np.array([[[1], [2]], [[3], [4]]])`           |
# | **nD Array** | n-dimensional (4D, 5D, etc.)  | Created using `np.array()` with higher nesting |


In [7]:
import numpy as np

np.array([[[1], [2]], [[3], [4]]])

array([[[1],
        [2]],

       [[3],
        [4]]])

In [9]:
#matrix:
# A matrix is essentially a fancy or specialized name for a 2D array — an array with rows and columns.
# In NumPy, a 2D array created using np.array([[1, 2], [3, 4]]) can be considered a matrix, even though technically it's just a 2-dimensional ndarray.

# creating a matrix:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#converting a list into numpy array(when we want to have a faster,better performance)
#creating arrays from python lists
#np.array([element1,element2,element3])
import numpy as np
arr=np.array([1,2,3,4])  #passed the list directly
print(arr)
#it has created 1-d array

In [17]:
mylist=[1,2,3,4]
import numpy as np
arr=np.array([mylist])  #passing the  name of the list
print(arr)
#it has created a 2-d array

[[1 2 3 4]]


In [19]:
# NumPy Array Creation with Default Values:
# | Function                | Description                                    | Example Code         | Output (Shape / Values)                |
# | ----------------------- | ---------------------------------------------- | -------------------- | -------------------------------------- |
# | `np.zeros(shape)`       | Creates array filled with **0**                | `np.zeros((2, 3))`   | `[[0. 0. 0.], [0. 0. 0.]]`             |
# | `np.ones(shape)`        | Creates array filled with **1**                | `np.ones((3, 2))`    | `[[1. 1.], [1. 1.], [1. 1.]]`          |
# | `np.empty(shape)`       | Creates array with **uninitialized values**    | `np.empty((2, 2))`   | May contain **random/garbage values**  |
# | `np.full(shape, value)` | Creates array filled with a **specific value** | `np.full((2, 3), 7)` | `[[7 7 7], [7 7 7]]`                   |
# | `np.eye(n)`             | Creates **identity matrix** (1s on diagonal)   | `np.eye(3)`          | `[[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]]` |


In [23]:
zerosarray=np.zeros((3,4))
print(zerosarray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
onesarray=np.ones((3,4))
print(onesarray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
emptyarray=np.empty((3,4))
print(emptyarray)

emptyarray2=np.empty((5,4))
print(emptyarray2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.46717037e-311 1.46717688e-311 1.46717688e-311 1.46717688e-311]
 [1.46717694e-311 1.46717694e-311 1.46717694e-311 1.46717694e-311]
 [1.46717694e-311 1.46717694e-311 1.46717691e-311 1.46717694e-311]
 [1.46717694e-311 1.46717694e-311 1.46717694e-311 1.46717694e-311]
 [1.46717694e-311 1.46717691e-311 1.46717694e-311 1.46717694e-311]]


In [45]:
fullarray=np.full((3,4),7)
print(fullarray)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [55]:
eyearray=np.eye((4))  #identity matrix with 4 ones
print(eyearray)

eyearray=np.eye((5))  #  #identity matrix with 5 ones
print(eyearray)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [1]:
#types of Arrays (in NumPy and general context)
# 1. Based on Dimensions (Number of Axes):
# | Array Type   | Description                   | Example                                        |
# | ------------ | ----------------------------- | ---------------------------------------------- |
# | **1D Array** | Single row or column (vector) | `np.array([1, 2, 3])`                          |
# | **2D Array** | Matrix (rows and columns)     | `np.array([[1, 2], [3, 4]])`                   |
# | **3D Array** | Stack of matrices             | `np.array([[[1], [2]], [[3], [4]]])`           |
# | **nD Array** | n-dimensional (4D, 5D, etc.)  | Created using `np.array()` with higher nesting |


# 2. Based on Content Initialization:
# | Function        | Description                                    |
# | --------------- | ---------------------------------------------- |
# | `np.array()`    | Creates array from list or tuple               |
# | `np.zeros()`    | Creates array filled with **zeros**            |
# | `np.ones()`     | Creates array filled with **ones**             |
# | `np.empty()`    | Creates uninitialized array (random values)    |
# | `np.arange()`   | Array with range of numbers (like `range()`)   |
# | `np.linspace()` | Evenly spaced values over a specified interval |
# | `np.identity()` | Creates identity matrix                        |
# | `np.eye()`      | Creates 2D array with 1s on diagonal           |


In [7]:
import numpy as np

eyearray2=np.eye(5,3)  #  #identity matrix with 5 ones
print(eyearray2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# | Feature              | `np.identity()`                          | `np.eye()`                                  |
# | -------------------- | ---------------------------------------- | ------------------------------------------- |
# | **Purpose**          | Creates a square identity matrix         | Creates a matrix with 1s on the diagonal    |
# | **Parameters**       | Takes **only one** parameter: `n` (size) | Takes **two**: `rows`, `columns` (optional) |
# | **Diagonal control** | Fixed (main diagonal only)               | Flexible: can shift diagonal using `k`      |
# | **Shape**            | Always **square** (n × n)                | Can be **non-square** (m × n)               |
# | **Function Type**    | Simpler, limited                         | More general and powerful                   |


#In the function np.eye(m,n, k=0), the k parameter controls which diagonal gets the 1s.
#example 1:
import numpy as np

# Main diagonal (k = 0)
print(np.eye(3, 3, k=0))
                                                                                        

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Diagonal above the main (k = 1)
print(np.eye(3, 4, k=1))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# Diagonal below the main (k = -1)
print(np.eye(3, 3, k=-1))


[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [3]:
#creating sequences of numbers in numpy:
# | **Function**          | **Purpose**                                    | **Syntax**                           | **Example**                 | **Output**                  |
# | --------------------- | ---------------------------------------------- | ------------------------------------ | --------------------------- | --------------------------- |
# | `np.arange()`         | Evenly spaced values within a range            | `np.arange(start, stop, step)`       | `np.arange(1, 10, 2)`       | `[1 3 5 7 9]`               |
# | `np.arange(n)`        | Sequence from 0 to n-1                         | `np.arange(stop)`                    | `np.arange(5)`              | `[0 1 2 3 4]`               |
# | `np.linspace()`       | `num` values evenly spaced over \[start, stop] | `np.linspace(start, stop, num)`      | `np.linspace(0, 1, 5)`      | `[0.   0.25 0.5  0.75 1. ]` |
# | `np.logspace()`       | `num` values spaced logarithmically            | `np.logspace(start, stop, num)`      | `np.logspace(1, 3, 3)`      | `[  10.  100. 1000.]`       |
# | `np.random.randint()` | Random sequence of integers                    | `np.random.randint(low, high, size)` | `np.random.randint(1,10,5)` | e.g. `[2 7 9 3 6]`          |
# | `np.random.rand()`    | Random floats in \[0, 1)                       | `np.random.rand(n)`                  | `np.random.rand(4)`         | e.g. `[0.3 0.7 0.1 0.5]`    |


In [19]:
# 1.np.arange()
# The function np.arange() is used to create a sequence of evenly spaced numbers within a given range by specifying the start, stop, and step values.
# (Note: The stop value is not included in the output.)


#syntax: arange(start,stop,step)
import numpy as np
print(np.arange(2,10,3))
print(np.arange(0,10,1))   #last limlit is excluded
print(np.arange(1,10,1))

[2 5 8]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [21]:
#np.arange(n)
#syntax: np.arange(stop)
print(np.arange(5))     #just give the last limit n, output will be array till n-1 elements

[0 1 2 3 4]


In [41]:
 #np.linspace()
# The function np.linspace() is used to create a sequence of evenly spaced numbers over a specified interval by specifying the start, stop,
#and the total number of values to generate.
# (Note: The stop value is included by default.)

print(np.linspace(2,4,8))
print("another example:")
print(np.linspace(1,2,5))

[2.         2.28571429 2.57142857 2.85714286 3.14285714 3.42857143
 3.71428571 4.        ]
another example:
[1.   1.25 1.5  1.75 2.  ]


In [49]:
# np.logspace():
# The function np.logspace() is used to create a sequence of numbers that increases exponentially.
# It’s useful when you want to create numbers that grow on a logarithmic scale, like 10¹, 10², 10³...
#np.logspace(start, stop, num=50, endpoint=True/False, base=10.0, dtype=None)



import numpy as np
arr=np.logspace(1,3,num=5,endpoint=True,base=10)
print(arr)


[  10.           31.6227766   100.          316.22776602 1000.        ]


In [53]:
import numpy as np
arr=np.logspace(2,3,num=5,endpoint=True,base=10)
print(arr)

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


In [63]:
import numpy as np
arr=np.logspace(1,4,num=5,endpoint=False,base=10)
print(arr)

[  10.           39.81071706  158.48931925  630.95734448 2511.88643151]


# NUMPY ARRAY PROPERTIES

In [ ]:
#Important Properties of a NumPy Array (ndarray)


# | **Property**       | **Description**                                                | **Example**                    |
# | ------------------ | -------------------------------------------------------------- | ------------------------------ |
# | `ndarray.ndim`     | Number of dimensions (axes) of the array                       | `arr.ndim` → `1`, `2`, `3`...  |
# | `ndarray.shape`    | Tuple showing the size in each dimension (rows, columns, etc.) | `arr.shape` → `(3, 4)`         |
# | `ndarray.size`     | Total number of elements in the array                          | `arr.size` → `12`              |
# | `ndarray.dtype`    | Data type of the array elements                                | `arr.dtype` → `int64`, `float` |
# | `ndarray.itemsize` | Size (in bytes) of each element in the array                   | `arr.itemsize` → `8`           |
# | `ndarray.nbytes`   | Total memory consumed by the array (size × itemsize)           | `arr.nbytes` → `96`            |
# | `ndarray.T`        | Transpose of the array (rows ↔ columns for 2D)                 | `arr.T`                        |
# | `ndarray.data`     | Memory location where the array is stored (rarely used)        | `arr.data`                     |


In [71]:
#1.shape:In NumPy, .shape is an attribute that tells you the dimensions (shape) of an array.
#It returns a tuple of integers which shows the number of elements along each dimension (axis) of the array.
import numpy as np
arr_2d=np.array([[1,2,3],
                [4,5,6]])
print(arr_2d)
print("shape is:")
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]]
shape is:
(2, 3)


In [75]:
#Examples:
#1. 1D Array
import numpy as np
a = np.array([1, 2, 3, 4])
print(a.shape)
#➡️ Means: 1 row, 4 columns — a 1D array with 4 elements.

(4,)


In [77]:
#2d array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
#Means: 2 rows, 3 columns.

(2, 3)


In [87]:
#3d array
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c.shape)
#Means: 2 blocks, each with 2 rows and 2 columns.

(2, 2, 2)


In [89]:
#NOTE
# arr.shape()  # ❌ This will give an error
# arr.shape    # ✅ No parentheses

# If you want a valid 3D array, all inner arrays must have the same size:
# c = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])



In [105]:
# ndarray.size
# it is an attribute that shows the total number of elements in the array

#1d array
import numpy as np
a = np.array([1, 2, 3, 4])
print(a.size)

4


In [101]:
#2d array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.size)

6


In [103]:
#3d array
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c.size)

8


In [113]:
#.ndim
#.ndim is an attribute of a NumPy array that tells us the number of dimensions (also called axes).

#1d array
import numpy as np
a = np.array([1, 2, 3, 4])
print(a.ndim)


#2d array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim)


#3d array
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c.ndim)

1
2
3


In [129]:
#.dtype
#.dtype is an attribute that tells you the data type of elements stored in a NumPy array.
#Example 1: Integer Array
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)


int32


In [131]:
import numpy as np
arr1 = np.array([1.1, 2, 3])
print(arr1.dtype)
#IF THERE ARE BOTH INT AND FLOATS, IT WILL SHOW THE RESULT AS FLOAT

float64


In [117]:
#Example 2: Float Array
arr = np.array([1.2, 3.5, 4.8])
print(arr.dtype)


float64


In [123]:
#Example 3: String Array
arr = np.array(["apple", "banana"])
print(arr.dtype)
#<U6 : Unicode string of length 6
#NOTE: "banana" is longer, NumPy chooses the longest string's length to decide the array's dtype

<U6


In [133]:
# astype(): its a method in numpy which converts the array to a different data type

# A method is a function that is attached to an object, like a NumPy array.
# So astype() is a method of the ndarray object (NumPy array).


#Example 1: Convert int to float
import numpy as np
arr = np.array([1, 2, 3])
new_arr = arr.astype(float)

print(new_arr)       # [1. 2. 3.]
print(new_arr.dtype) # float64


[1. 2. 3.]
float64


In [137]:
#Example 2: Convert float to int
import numpy as np
con=np.array([1.2,2.3,3.4,4.4,5.6])
newcon=con.astype(int)
print(newcon)

[1 2 3 4 5]


In [141]:
#Example 3: Convert int to string
arr3 = np.array([1, 2, 3])
new_arr = arr3.astype(str)

print(new_arr)       # [1 2 3]
print(new_arr.dtype) # int32 or int64


['1' '2' '3']
<U11


In [145]:
#Example 3: Convert string to int
arr4 = np.array(["1", "2", "3"])
new_arr = arr4.astype(int)

print(new_arr)       # [1 2 3]
print(new_arr.dtype) # int32 or int64


[1 2 3]
int32


In [149]:
#Example 5: Convert float to string
arr5 = np.array([1.2, 2.3, 3.4])
new_arr = arr5.astype(str)

print(new_arr)       # [1 2 3]
print(new_arr.dtype) # int32 or int64

['1.2' '2.3' '3.4']
<U32


In [155]:
#.T : array.T is an attribute that returns the transpose of a NumPy array.
# 🔸 What is transpose?
# Transpose means flipping the array over its diagonal, so that:
# Rows become columns
# Columns become rows
import numpy as np
transpose=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(transpose)
print(transpose.T)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[ 1 10 90]
 [ 2 20 80]
 [ 3 30 70]
 [ 4 40 60]]


# NumPy Array Operations

In [160]:
# 1. Arithmetic Operations
# | Operation          | Syntax     | Example    | Output                                                  |
# | ------------------ | ---------- | ---------- | ------------------------------------------------------- |
# | Addition           | `arr + x`  | `arr + 5`  | Adds 5 to each element                                  |
# | Subtraction        | `arr - x`  | `arr - 2`  | Subtracts 2 from each element                           |
# | Multiplication     | `arr * x`  | `arr * 3`  | Multiplies each element by 3                            |
# | Division           | `arr / x`  | `arr / 2`  | Divides each element by 2 (float)                       |
# | **Floor Division** | `arr // x` | `arr // 2` | Divides and returns **whole number** (removes decimals) |
# | Power              | `arr ** x` | `arr ** 2` | Squares each element                                    |
#addition
import numpy as np
operadd=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(operadd)
print(operadd+5)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[ 6  7  8  9]
 [15 25 35 45]
 [95 85 75 65]]


In [162]:
#subtraction
import numpy as np
opersub=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(opersub)
print(opersub-5)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[-4 -3 -2 -1]
 [ 5 15 25 35]
 [85 75 65 55]]


In [168]:
#multiplication
import numpy as np
opermul=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(opermul)
print(opermul*5)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[  5  10  15  20]
 [ 50 100 150 200]
 [450 400 350 300]]


In [178]:
import numpy as np
arrayop=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(arrayop)
print(arrayop+5)
print(arrayop**2)
print(arrayop*3)
print(arrayop//5)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[ 6  7  8  9]
 [15 25 35 45]
 [95 85 75 65]]
[[   1    4    9   16]
 [ 100  400  900 1600]
 [8100 6400 4900 3600]]
[[  3   6   9  12]
 [ 30  60  90 120]
 [270 240 210 180]]
[[ 0  0  0  0]
 [ 2  4  6  8]
 [18 16 14 12]]


In [190]:
 #2. Comparison Operations
# It compares each element of an array with a value or another array.
# The result is a Boolean array: True or False for each comparison.
# | Operation             | Syntax     | Example    | Output                |
# | --------------------- | ---------- | ---------- | --------------------- |
# | Greater than          | `arr > x`  | `arr > 2`  | `[False False  True]` |
# | Less than             | `arr < x`  | `arr < 3`  | `[ True  True False]` |
# | Equal to              | `arr == x` | `arr == 2` | `[False  True False]` |
# | Not equal to          | `arr != x` | `arr != 2` | `[ True False  True]` |
# | Greater than or equal | `arr >= x` | `arr >= 2` | `[False  True  True]` |
# | Less than or equal    | `arr <= x` | `arr <= 2` | `[ True  True False]` |
#example
import numpy as np
comparray=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(comparray)
print(comparray>10)
print(comparray<10)
print(comparray>=30)

[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [204]:
# 3. Aggregate Functions
# An aggregate function in NumPy is a function that takes many values in an array and gives one single result (like total, average, max, etc.).
# | Function     | Purpose             | Example              |
# | ------------ | ------------------- | -------------------- |
# | `arr.sum()`  | Sum of all elements | `arr.sum()` → `6`    |
# | `arr.mean()` | Average of elements | `arr.mean()` → `2.0` |
# | `arr.min()`  | Minimum value       | `arr.min()` → `1`    |
# | `arr.max()`  | Maximum value       | `arr.max()` → `3`    |
# | `arr.std()`  | Standard deviation  | `arr.std()` → `0.82` |
# |  arr.var()   |variation  | syntax:np.var(arr) or arr.var()|




import numpy as np
aggrarray=np.array([[1,2,3,4],
                   [10,20,30,40],
                   [90,80,70,60]])
print(aggrarray)
print(aggrarray.sum())
print(aggrarray.max())
print(aggrarray.min())
print(aggrarray.mean())
print(aggrarray.std())


#Standard deviation:
#it tells us how spread out the numbers are from the mean (average).
# If numbers are close to the mean, the standard deviation is small ✅
#If numbers are spread out far from the mean, the standard deviation is large ❌



#Variance:Variance measures how far each number in a dataset is from the mean
# If all numbers are close to the mean, variance is low
# If numbers are very different from the mean, variance is high

# for the array: [2, 4, 6, 8]
# Mean = 5
# Differences from mean = [-3, -1, 1, 3]
# Squared differences = [9, 1, 1, 9]
# Variance = Average of these 
#just read : and it squares those differences to avoid negative values.



# Relationship:
# Standard Deviation=square root of variance or
# variance=square of std

# | Term                   | Meaning                                                              |
# | ---------------------- | -------------------------------------------------------------------- |
# | **Variance**           | Measures spread using **squared differences** from mean              |
# | **Standard Deviation** | Measures spread using **original differences** from mean (no square) |


[[ 1  2  3  4]
 [10 20 30 40]
 [90 80 70 60]]
410
90
1
34.166666666666664
31.651312066888405


In [ ]:
 4. Array-wise Operations
# | Operation          | NumPy Function          | Example                           | Output     |
# | ------------------ | ----------------------- | --------------------------------- | ---------- |
# | Addition           | `np.add(a, b)`          | `np.add([1, 2], [3, 4])`          | `[4, 6]`   |
# | Subtraction        | `np.subtract(a, b)`     | `np.subtract([3, 5], [1, 2])`     | `[2, 3]`   |
# | Multiplication     | `np.multiply(a, b)`     | `np.multiply([1, 2], [3, 4])`     | `[3, 8]`   |
# | Division           | `np.divide(a, b)`       | `np.divide([6, 8], [2, 4])`       | `[3., 2.]` |
# | **Floor Division** | `np.floor_divide(a, b)` | `np.floor_divide([7, 9], [2, 4])` | `[3, 2]`   |
# | **Power**          | `np.power(a, b)`        | `np.power([2, 3], 2)`             | `[4, 9]`   |
# | Dot Product        | `np.dot(a, b)`          | `np.dot([[1, 2]], [[3], [4]])`    | `[[11]]`   |


In [ ]:
# 5. Reshaping and Flattening
# | Function        | Purpose                            | Example             |
# | --------------- | ---------------------------------- | ------------------- |
# | `arr.reshape()` | Change shape without changing data | `arr.reshape(3, 2)` |
# | `arr.flatten()` | Convert multi-dimensional to 1D    | `arr.flatten()`     |
