In [7]:
#numpy preprocessing
import numpy as np
lending_array=np.loadtxt("Lending-company-Numeric.csv",delimiter=",") #this loadtxt function cant load files which has null values inside it, for that "genfromtxt" function is used
lending_array

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [11]:
#to check null value anywhere in a particular array
np.isnan(lending_array).sum()  #give count for true value

0

In [15]:
lending_array=np.loadtxt("Lending-company-Numeric-NAN.csv",delimiter=",") 

ValueError: could not convert string '2000;40;365;3121;4241;13621' to float64 at row 0, column 1.

In [17]:
lending_array_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";")

In [19]:
np.isnan(lending_array_nan).sum() #checking null

260

In [23]:
lending_array_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";",filling_values=0)
np.isnan(lending_array_nan).sum()

0

In [27]:
np.max(lending_array_nan)   #if we did not have remove tyhe null value then the max value will be nan only, so nan value must be removed first

64001.0

In [45]:
tempfillvalues=np.nanmax(lending_array_nan)+4   # 4 more than max
#fill values 64005
tempfillvalues

64005.0

In [33]:
lending_array_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";",filling_values=tempfillvalues)

lending_array_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4005e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]])

In [35]:
np.nanmean(lending_array_nan,axis=0)

array([ 4263.34611697,  2989.56375839,  3537.84755513,  7469.10738255,
        7304.64525407, 17753.86481304])

In [37]:
np.nanmean(lending_array_nan,axis=0).round(2)

array([ 4263.35,  2989.56,  3537.85,  7469.11,  7304.65, 17753.86])

In [39]:
np.nanmean(lending_array_nan,axis=0).round(3)

array([ 4263.346,  2989.564,  3537.848,  7469.107,  7304.645, 17753.865])

In [41]:
np.nanmean(lending_array_nan,axis=0).round(1)

array([ 4263.3,  2989.6,  3537.8,  7469.1,  7304.6, 17753.9])

In [43]:
lending_array_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";")
np.nanmean(lending_array_nan,axis=0).round(2)

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [57]:
temp_mean=np.nanmean(lending_array_nan,axis=0).round(2)
print(temp_mean)
print(temp_mean[0])

[ 2250.25    46.11   365.    3895.99  5160.75 16571.44]
2250.25


In [65]:
lending_array_nan=np.genfromtxt("Lending-company-Numeric-NAN.csv",delimiter=";",filling_values=temp_mean[0])
lending_array_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [71]:
import numpy as np

# Load the data with NaNs preserved
lending_array_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter=";")

# Step 1: Compute the column-wise means (ignoring NaNs)
col_means = np.nanmean(lending_array_nan, axis=0)

# Step 2: Find where NaNs are located
nan_indices = np.where(np.isnan(lending_array_nan))

# Step 3: Replace NaNs with the corresponding column mean
lending_array_nan[nan_indices] = np.take(col_means, nan_indices[1])

# Step 4: (Optional) Round for cleaner results
lending_array_nan = np.round(lending_array_nan, 2)

# Final array with all NaNs filled using their respective column means
print(lending_array_nan)


[[ 2000.      40.     365.    3121.    4241.   13621.  ]
 [ 2000.      40.     365.    3061.    4171.   15041.  ]
 [ 1000.      40.     365.    2160.    3280.   15340.  ]
 ...
 [ 2250.25    40.     365.    4201.    5001.   16600.  ]
 [ 1000.      40.     365.    2080.    3320.   15600.  ]
 [ 2000.      40.     365.    4601.    4601.   16600.  ]]


In [89]:
import numpy as np

data = np.genfromtxt("loan-data.csv", delimiter=";")
print(data)



[[          nan           nan           nan ...           nan
            nan           nan]
 [4.8010226e+07           nan 3.5000000e+04 ...           nan
            nan 9.4529600e+03]
 [5.7693261e+07           nan 3.0000000e+04 ...           nan
            nan 4.6797000e+03]
 ...
 [5.0415990e+07           nan 1.0000000e+04 ...           nan
            nan 2.1856400e+03]
 [4.6154151e+07           nan           nan ...           nan
            nan 3.1994000e+03]
 [6.6055249e+07           nan 1.0000000e+04 ...           nan
            nan 3.0190000e+02]]


In [91]:
np.isnan(data).sum()  

88019

In [93]:
np.max(data)

nan

In [95]:
tempfillvalue=np.nanmax(data)+4   # 4 more than max
#fill values 64005
tempfillvalue

68616523.0