In [9]:
# NumPy was developed by Travis Oliphant in 2005.
#numpy is a library of python through  which we can handle large amount of data using arrays instead of list.
#it is used to perform arithmetic calculation on numeric data.


#C is the fastest programming language because it is closest to hardware, it is used for OS,
#embedded system(An embedded system is a small computer built into a device to perform a specific task.).
# Washing Machine	Controls washing cycles
# Microwave Oven	Manages heating and timing

# Universal Function (ufunc) in NumPy =
# A built-in, fast, vectorized function that performs element-wise operations on arrays.
# It’s written in C for speed, but you call it like normal Python functions.
#Universal function: functions that can be applied over each elements

# | Category            | Function Examples                       |
# | ------------------- | --------------------------------------- |
# | **Arithmetic**      | `add`, `subtract`, `multiply`, `divide` |
# | **Trigonometric**   | `sin`, `cos`, `tan`                     |
# | **Exponential/Log** | `exp`, `log`, `log10`                   |
# | **Comparison**      | `greater`, `less`, `equal`              |
# | **Statistical**     | `minimum`, `maximum`, `mean`, `std`     |



# Why do people still use Python if it's slower?
# Python is easy to write and learn.

# Python is good for prototyping.

# Many libraries like NumPy, TensorFlow, PyTorch use C/C++ internally for speed but give Python interface for simplicity.

# NumPy and C: How are they related?
# NumPy is a Python library, but internally, it uses C language for the heavy work (like calculations).

# That’s why NumPy is very fast compared to normal Python loops.


#Numpy stands for numerical python

# NumPy Overview
# NumPy uses arrays to perform operations and store data efficiently.

# Why Arrays?
# Arrays store data in continuous memory locations.
# This makes data access faster compared to Python lists.

# Key Advantages of NumPy Arrays(its the difference also between lists and arrays):
# Speed: Much faster than lists for numerical tasks.
# Efficiency: Consumes less memory due to continuous memory allocation.
# Convenient Operations: Supports mathematical operations like addition, multiplication, and trigonometric functions directly on arrays.

# Definition:
# Broadcasting in NumPy is the ability to perform element-wise operations on arrays of different shapes — by automatically expanding 
#the smaller array to match the shape of the larger one.
# 🎯 In Simple Words:# You can add, subtract, multiply, etc., arrays of different shapes, and NumPy will stretch the smaller array without copying data.

In [7]:
import numpy as np
temperatures=np.array([32.5,31.8,33.0,35.2,36.6])
average=np.mean(temperatures)
print(average)

33.82


In [11]:
# features of numpy: 
# 1. consumes less memory
# 2. easy math operation
# 3. used in almost all data fields AI,DS,Data Analysis


In [13]:
# Use of Numpy:
# 1.Data Science
# 2.Machine Learning and AI(used in tensorflow and pytorch)
# 3.Stock market and finance
# 4.Image processing(photoshop tools)
# 5. Scientific Computing
# Solving mathematical problems: linear algebra, calculus,
# 6. Deep Learning
# Creating input data structures (e.g., image tensors)
# Normalization and augmentation of data
# 7. Mathematical Computations
# Matrix multiplication, inversion, dot products
# Statistical functions (mean, median, std)
# 8. Computer Graphics & Simulations
# Modeling transformations in 2D/3D space
# Creating simulations using multi-dimensional arrays

In [1]:
#  difference between Python Lists and NumPy Arrays
#A NumPy ndarray (n-dimensional array) is the primary data structure of the NumPy library, used to store elements of the same data type in effiecient way
#in a multidimensional format. It is faster than actual list,uses less memory and perform mathematical operations directly without using any loop.


# | Feature                      | **Python List**                                                       | **NumPy Array**                                                      |
# | ---------------------------- | --------------------------------------------------------------------- | -------------------------------------------------------------------- |
# |Actual existence?             | Built-in data structure                                               |  Provided by NumPy library
# | **Data Type**                | **Heterogeneous** – can store different types (int, float, str, etc.) | **Homogeneous** – all elements must be of the same type              |
# | **Speed**                    | Slower – not optimized for numerical computation                      | Faster – optimized using C backend and vectorized operations         |
# | **Memory Efficiency**        | Consumes more memory due to dynamic typing                            | Consumes less memory – fixed data types and continuous memory        |
# | **Mathematical Operations**  | Not supported directly (e.g., `a + b` concatenates lists)             | Element-wise operations (e.g., `a + b` adds elements)                |
# | **Functionality**            | Basic: append, pop, slice, etc.                                       | Rich:broadcasting, statistical operations, reshaping       |
# | **Indexing**                 | Basic (single level)                                                  | Advanced (multi-dimensional)                |

#In NumPy, multidimensional indexing lets you access elements in arrays with 2 or more dimensions using row and column indices, or even more.

In [7]:
python_list=[1,2,3,4,5]
print(python_list)

import numpy as np
numpy_array=np.array([1,2,3,4,5])
print(numpy_array)


# Printing a Python list shows elements separated by commas,
# while printing a NumPy array shows elements separated by spaces (no commas).

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [1]:
# An array is a data structure that stores elements of the same data type in a fixed-size, indexed, and ordered format.
# A fixed-size array means that once an array is created, its size (number of elements) cannot be changed directly.

# In Python, arrays are commonly created using the NumPy library, where they are called ndarray and support multi-dimensional storage 
# and fast numerical computations.

In [3]:
# | Array Type   | Description                   | Example                                        |
# | ------------ | ----------------------------- | ---------------------------------------------- |
# | **1D Array** | Single row or column (vector) | `np.array([1, 2, 3])`                          |
# | **2D Array** | Matrix (rows and columns)     | `np.array([[1, 2], [3, 4]])`                   |
# | **3D Array** | Stack of matrices/2d-arrays   | `np.array([[[1], [2]], [[3], [4]]])`           |
# | **nD Array** | n-dimensional (4D, 5D, etc.)  | Created using `np.array()` with higher nesting |


In [7]:
import numpy as np

np.array([[[1], [2]], [[3], [4]]])

array([[[1],
        [2]],

       [[3],
        [4]]])

In [9]:
#matrix:
# A matrix is essentially a fancy or specialized name for a 2D array — an array with rows and columns.
# In NumPy, a 2D array created using np.array([[1, 2], [3, 4]]) can be considered a matrix, even though technically it's just a 2-dimensional ndarray.

# creating a matrix:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
#converting a list into numpy array(when we want to have a faster,better performance)
#creating arrays from python lists
#np.array([element1,element2,element3])
import numpy as np
arr=np.array([1,2,3,4])  #passed the list directly
print(arr)
#it has created 1-d array

In [17]:
mylist=[1,2,3,4]
import numpy as np
arr=np.array([mylist])  #passing the  name of the list
print(arr)
#it has created a 2-d array

[[1 2 3 4]]


In [19]:
# NumPy Array Creation with Default Values:
# | Function                | Description                                    | Example Code         | Output (Shape / Values)                |
# | ----------------------- | ---------------------------------------------- | -------------------- | -------------------------------------- |
# | `np.zeros(shape)`       | Creates array filled with **0**                | `np.zeros((2, 3))`   | `[[0. 0. 0.], [0. 0. 0.]]`             |
# | `np.ones(shape)`        | Creates array filled with **1**                | `np.ones((3, 2))`    | `[[1. 1.], [1. 1.], [1. 1.]]`          |
# | `np.empty(shape)`       | Creates array with **uninitialized values**    | `np.empty((2, 2))`   | May contain **random/garbage values**  |
# | `np.full(shape, value)` | Creates array filled with a **specific value** | `np.full((2, 3), 7)` | `[[7 7 7], [7 7 7]]`                   |
# | `np.eye(n)`             | Creates **identity matrix** (1s on diagonal)   | `np.eye(3)`          | `[[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]]` |


In [23]:
zerosarray=np.zeros((3,4))
print(zerosarray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
onesarray=np.ones((3,4))
print(onesarray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
emptyarray=np.empty((3,4))
print(emptyarray)

emptyarray2=np.empty((5,4))
print(emptyarray2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.46717037e-311 1.46717688e-311 1.46717688e-311 1.46717688e-311]
 [1.46717694e-311 1.46717694e-311 1.46717694e-311 1.46717694e-311]
 [1.46717694e-311 1.46717694e-311 1.46717691e-311 1.46717694e-311]
 [1.46717694e-311 1.46717694e-311 1.46717694e-311 1.46717694e-311]
 [1.46717694e-311 1.46717691e-311 1.46717694e-311 1.46717694e-311]]


In [45]:
fullarray=np.full((3,4),7)
print(fullarray)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [55]:
eyearray=np.eye((4))  #identity matrix with 4 ones
print(eyearray)

eyearray=np.eye((5))  #  #identity matrix with 5 ones
print(eyearray)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
