In [11]:
#C is the fastest programming language because it is closest to hardware, it is used for OS,
#embedded system(An embedded system is a small computer built into a device to perform a specific task.).
# Washing Machine	Controls washing cycles
# Microwave Oven	Manages heating and timing

# Universal Function (ufunc) in NumPy =
# A built-in, fast, vectorized function that performs element-wise operations on arrays.
# It’s written in C for speed, but you call it like normal Python functions.
#Universal function: functions that can be applied over each elements

# | Category            | Function Examples                       |
# | ------------------- | --------------------------------------- |
# | **Arithmetic**      | `add`, `subtract`, `multiply`, `divide` |
# | **Trigonometric**   | `sin`, `cos`, `tan`                     |
# | **Exponential/Log** | `exp`, `log`, `log10`                   |
# | **Comparison**      | `greater`, `less`, `equal`              |
# | **Statistical**     | `minimum`, `maximum`, `mean`, `std`     |

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.add(arr1, arr2))       # [5 7 9]
print(np.multiply(arr1, arr2))  # [ 4 10 18]
print(np.subtract(arr2, arr1))  # [3 3 3]





[5 7 9]
[ 4 10 18]
[3 3 3]


In [5]:
# Why do people still use Python if it's slower?
# Python is easy to write and learn.

# Python is good for prototyping.

# Many libraries like NumPy, TensorFlow, PyTorch use C/C++ internally for speed but give Python interface for simplicity.

# NumPy and C: How are they related?
# NumPy is a Python library, but internally, it uses C language for the heavy work (like calculations).

# That’s why NumPy is very fast compared to normal Python loops.

In [7]:
#Broadcasting:
#broadcasting is NumPy's ability to “stretch” or “replicate” smaller arrays to match the dimensions of larger ones during arithmetic operations

# Broadcasting Rule (Official Definition):

# Two arrays are compatible for broadcasting if, for each dimension (starting from the right):
# The dimensions are equal, or
# One of the dimensions is 1 (it will be stretched to match the other).


#Broadcasting operation
import numpy as np
arr=np.array([10,20,30])
arr1=np.array([[10,20,30],[40,50,60]])
arr+arr1
#here arr has stretched its size as per the size of arr1

array([[20, 40, 60],
       [50, 70, 90]])

In [9]:
arr=np.array([[10],
               [20]])
arr1=np.array([[10,20,30],
               [40,50,60]])
arr+arr1


array([[20, 30, 40],
       [60, 70, 80]])

In [13]:
#Add a 1D array to a 2D array

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C=A+B
print(C)

[[11 22 33]
 [14 25 36]]


In [17]:
# Multiply a column vector with a row vector
#**Row vectors and column vectors in NumPy are usually represented as 2D arrays.
# | **Vector Type**   | **Shape in NumPy** | **Example**       |
# | ----------------- | ------------------ | ----------------- |
# | **Row Vector**    | (1, n) → **2D**    | `[[1, 2, 3]]`     |
# | **Column Vector** | (n, 1) → **2D**    | `[[1], [2], [3]]` |
# SO... [1,2,3] is 1d array and its not a row vector

import numpy as np

A = np.array([[1],
              [2],
              [3]],
            )

B = np.array([[10, 20, 30]])
C=A*B
print(C)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [23]:
#Example 1: Different Row & Column Means

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Row-wise mean
print(np.mean(arr, axis=1))   # [2. 5. 8.]

# Column-wise mean
print(np.mean(arr, axis=0))   # [4. 5. 6.]

# Overall mean
print(np.mean(arr))           # 5.0


[2. 5. 8.]
[4. 5. 6.]
5.0


In [35]:
# Subtract means from rows elements from mean of each row
import numpy as np
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
B1=np.mean(A[0])
print(B1)
B2=np.mean(A[1])
print(B2)
B3=np.mean(A[2])
print(B3)

C=A-np.array([[B1],
    [B2],
    [B3]])
print(C)

2.0
5.0
8.0
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
